### ISSUE TITLE
Is it this book outdated ?

### ISSUE THREAD

**Issue by Mabachess** [PacktPublishing/Learning_DevOps#32]
It was a gift  from family about my SRE work.
But, i looked inside some DevSecOps and bbest practices about Devops manifest.
This book sound pretty good, but i am surprised, they are not up to date.
What happened ?
Kinds regards,
M7s

**Comment by rajat-packt** [comment]
Hey @Mabachess this book was published in 2019, there are bound to be somethings that get outdated in the span of 2 years.
But, if you can provide details regarding the issues that you are facing we can try contacting the author and getting them to resolve your queries.

**Comment by Mabachess** [comment]
I just want to participate by updating the repository, learning about more DevOps best pratices.
This book, and that did @mikaelkrief are pretty nice. Just to tel you about this. Thank a lot and kinds regards

**Comment by rajat-packt** [comment]
Happy to know you liked the book.
Unfortunately, continuously updating the repository is not very practical after the book is published, especially after 2 years.
But please feel free to fork the repo and implement your changes there. 
While we can't update this repo right now, the second edition of this book is in the works now and should be available earliest by the second half of March, hopefully that will help in resolving all the outdated exercises.

**Comment by Mabachess** [comment]
Preety nice!
Awating about this seecond edition
Hope i can buy it quickly for upgrade best pratices.
We can close this issue. Thanks a lot @rajat-packt

**Comment by tkolstee** [comment]
Just bought this book through Amazon and didn't know that a new edition was due to come out so soon.

Presently I'm still in the chapter 2 Terraform examples. This is full of things that don't run correctly. Can anyone give me an idea what to expect? Are there breaking changes in the rest of the tooling or is Terraform syntax changing more rapidly than most?

Will the first and second editions be structured similarly enough that I can work through the first edition using the second edition's code as a reference? I'd hate to have to buy the book all over again...
